name: Package WordPress Plugin

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Build plugin
        run: npm run build

      - name: Create plugin zip
        run: npm run plugin-zip

      - name: Get package info
        id: package
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Upload plugin zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.name }}-${{ steps.package.outputs.version }}
          path: "*.zip"
